name: windows/checkout_abseil
description: 'Checks out the abseil-cpp header files on Windows.'
runs:
  using: 'composite'
  steps:
    - uses: mockingbirdnest/actions/windows/checkout_dependency@main
      with:
        name: abseil-cpp
        ref: master
        headers_directory: absl
        solution_directory: msvc
