name: windows/restore
description: 'Restores a solution on Windows.'
inputs:
  configuration:
    description: 'The configuration (Debug, Release, etc.) to restore.'
    required: true
  solution_directory:
    description: 'The path where the MSVC solution is located.'
    required: true
runs:
  using: 'composite'
  steps:
    - run: >
        ls ${{ inputs.solution_directory }}\*.sln | %
        {
        &"${{ env.PRINCIPIA_MSBUILD_PATH }}"
        /target:Restore
        /property:Configuration=${{ inputs.configuration }}
        $_
        }
      shell: pwsh
      env:
        PRINCIPIA_MSBUILD_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe
