name: windows/rebuild
description: 'Rebuilds a solution on Windows.'
inputs:
  configuration:
    description: 'The configuration (Debug, Release, etc.) to build.'
    required: true
  solution_directory:
    description: 'The path where the MSVC solution is located.'
    required: true
runs:
  using: 'composite'
  steps:
    - run: |
        $max_cpu_count = [Math]::Ceiling((Get-CimInstance Win32_ComputerSystem).NumberOfLogicalProcessors / 4)
        ls ${{ inputs.solution_directory }}\*.sln | % {
          $last_error = @{}
          $skip_note = @{}
          $done = $false
          $id = 0
          &"${{ env.PRINCIPIA_MSBUILD_PATH }}"                `
          /target:"Clean;Build"                               `
          /maxCpuCount:$max_cpu_count                         `
          /property:Configuration=${{ inputs.configuration }} `
          /property:Platform=x64                              `
          /property:UseMultiToolTask=true                     `
          /property:EnforceProcessCountAcrossBuilds=true      `
          $_
          | % {
            Write-Output $_
            if ($done -or $_ -eq 'Build FAILED.') {
              $done = $true
              return
            }
            if ($_ -match '\s+(?<id>\d+)>') {
              $id = $Matches.id
            }
            if ($_ -match '^\s+\d+>\w+:$') {
              return
            }
            if ($_ -match "\s*(?<location>(?<file>[^>]*)\((?<line>\d+),(?<column>\d+)\)): (?<title>(?<type>error|warning|message|note)[^:]*): (?<message>.*)") {
              if ($Matches.type -in @('error', 'warning')) {
                if ($last_error[$id]) {
                  Write-Output $last_error[$id]
                }
                $last_error[$id] = $null
                $skip_note[$id] = $false
                if ($Matches.title -eq 'error C2220') {
                  return
                }
                if ($Matches.file.StartsWith($PWD)) {
                  $last_error[$id] = "::$($Matches.type) file=$($Matches.file),line=$($Matches.line),col=$($Matches.column),title=$($Matches.title)::$($Matches.message)"
                } else {
                  $last_error[$id] = "::$($Matches.type) file={file},line={line},col={column},title=$($Matches.title)::$($Matches.location):%0A$($Matches.message)"
                }
              } elseif ($last_error[$id]) {
                if ($Matches.file.StartsWith($PWD)) {
                  if ($_.Contains("see reference") -or $_.Contains("see the first reference")) {
                    $last_error[$id] = $last_error[$id].Replace('{file}', $Matches.file).Replace('{line}', $Matches.line).Replace('{column}', $Matches.column)
                  }
                  $last_error[$id] += "%0A$($Matches.title): $($Matches.message)"
                } else {
                  $skip_note[$id] = $true
                }
              } else {
                Write-Output "::$($Matches.type -replace 'message|note','error') file=$($Matches.file),line=$($Matches.line),col=$($Matches.column),title=$($Matches.title)::$($Matches.message)"
              }
            } elseif ($last_error[$id] -and -not $skip_note[$id]) {
              if ($_.StartsWith('                 ')) {
                $last_error[$id] += "%0A$_"
              } else {
                Write-Output $last_error[$id]
                $last_error[$id] = $null
                $skip_note[$id] = $false
              }
            }
          }
          Write-Output $last_error.Values 
        }
      shell: pwsh
      env:
        PRINCIPIA_MSBUILD_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe
