name: windows/rebuild
description: 'Rebuilds a solution on Windows.'
inputs:
  configuration:
    description: 'The configuration (Debug, Release, etc.) to build.'
    required: true
  solution_directory:
    description: 'The path where the MSVC solution is located.'
    required: true
runs:
  using: 'composite'
  steps:
    - run: >
        $max_cpu_count = (Get-CimInstance Win32_ComputerSystem).NumberOfLogicalProcessors / 2
        ls ${{ inputs.solution_directory }}\*.sln | %
        {
        &"${{ env.PRINCIPIA_MSBUILD_PATH }}"
        /target:"Clean;Build"
        /maxCpuCount:$max_cpu_count
        /property:Configuration=${{ inputs.configuration }}
        /property:Platform=x64
        $_
        }
      shell: pwsh
      env:
        PRINCIPIA_MSBUILD_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe
