name: windows/rebuild
description: 'Rebuilds a solution on Windows.'
inputs:
  configuration:
    description: 'The configuration (Debug, Release, etc.) to build.'
    required: true
  solution_directory:
    description: 'The path where the MSVC solution is located.'
    required: true
runs:
  using: 'composite'
  steps:
    - run: |
        &"$env:GITHUB_ACTION_PATH/parse_msbuild.ps1"
        $max_cpu_count = [Math]::Ceiling((Get-CimInstance Win32_ComputerSystem).NumberOfLogicalProcessors / 4)
        ls ${{ inputs.solution_directory }}\*.sln | % {
          &"${{ env.PRINCIPIA_MSBUILD_PATH }}"                `
          /target:"Clean;Build"                               `
          /maxCpuCount:$max_cpu_count                         `
          /property:Configuration=${{ inputs.configuration }} `
          /property:Platform=x64                              `
          /property:UseMultiToolTask=true                     `
          /property:EnforceProcessCountAcrossBuilds=true      `
          /distributedFileLogger	                            `
          /consoleloggerparameters:ShowEventId                `
          $_
          | Parse-MSBuild
        }
      shell: pwsh
      env:
        PRINCIPIA_MSBUILD_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe
