name: windows/rebuild
description: 'Rebuilds a solution on Windows.'
inputs:
  configuration:
    description: 'The configuration (Debug, Release, etc.) to build.'
    required: true
  solution_directory:
    description: 'The path where the MSVC solution is located.'
    required: true
runs:
  using: 'composite'
  steps:
    - run: |
        $max_cpu_count = [Math]::Ceiling((Get-CimInstance Win32_ComputerSystem).NumberOfLogicalProcessors / 4)
        $last_error = @{}
        $id = 0
        ls ${{ inputs.solution_directory }}\*.sln | % {                                                   `
          &"${{ env.PRINCIPIA_MSBUILD_PATH }}"                `
          /target:"Clean;Build"                               `
          /maxCpuCount:$max_cpu_count                         `
          /property:Configuration=${{ inputs.configuration }} `
          /property:Platform=x64                              `
          /property:UseMultiToolTask=true                     `
          /property:EnforceProcessCountAcrossBuilds=true      `
          $_
          | % {
            Write-Output $_
            if ($_ -match '\s+(?<id>\d+)>') {
              $id = $Matches.id
            }
            if ($_ -match "(?<file>[^>]*)\((?<line>\d+),(?<column>\d+)\): (?<title>(?<type>error|warning|message|note)[^:]*): (?<message>.*)") {
              if ($Matches.type -in @('error', 'warning')) {
                if ($last_error[$id]) {
                  Write-Output $last_error[$id]
                }
                $last_error[$id] = $null
                if (-not $Matches.file.StartWith($PWD)) {
                  $last_error[$id] = "::$($Matches.type) file={file},line={line},col={column},title=$($Matches.title)::$($Matches.message)"
                }
              }
              if ($last_error[$id]) {
                if ($Matches.file.StartsWith($PWD)) {
                  $last_error[$id] = $last_error[$id].Replace('{file}', $Matches.file).Replace('{line}', $Matches.line).Replace('{column}', $Matches.column)
                }
                $last_error[$id] += "%0A$($Matches.title): $($Matches.message)"
              } else {
                Write-Output "::$($Matches.type -replace 'message|note','error') file=$($Matches.file),line=$($Matches.line),col=$($Matches.column),title=$($Matches.title)::$($Matches.message)"
              }
            } elseif ($last_error[$id]) {
              if ($_.StartsWith('                 ')) {
                $last_error[$id] += "%0A$_"
              } else {
                Write-Output $last_error[$id]
                $last_error[$id] = $null
              }
            }
          }
        }
        Write-Output $last_error.Values
      shell: pwsh
      env:
        PRINCIPIA_MSBUILD_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe
