name: windows/upload_principia_artifact
description: 'Upload a Principia build artifact.'
inputs:
  configuration:
    description: 'The configuration (Debug, Release, etc.) to build.'
    required: true
runs:
  using: 'composite'
  steps:
    - run: |
        echo "PRINCIPIA_ARTIFACT_NAME=${{ inputs.configuration}}-$(git describe --tags --always --dirty --abbrev=40 --long)" `
          >> $env:GITHUB_ENV
      shell: pwsh
    - uses: actions/upload-artifact@v3
      with:
        name: principia_${{ env.PRINCIPIA_ARTIFACT_NAME }}
        # The * after GameData is to preserve that directory in the artifact.
        path: ${{ inputs.configuration }}/GameData*
